### ISSUE TITLE
Compiling on node >0.10

### ISSUE THREAD

**Issue by mlaurijsse** [illegalprime/alsa-monitor-node#2]
Hi,

I couldn't compile your module on node versions > 0.10. So I've rewritten some parts using Nan, it's now tested and working with Node 0.10.43, 0.12.12 and 5.9.1.

If you'd like, I could send you a pull request. One disclaimer, I'm new to V8/Nan, so might be wise to use your expertise to double check for pitfalls.

Kind regards,

Marcel

**Comment by illegalprime** [comment]
Hi @mlaurijsse sorry for the late reply, I've been at school. This sounds like a great PR and I'd be happy to review it to be merged in.

**Comment by mlaurijsse** [comment]
Hi, thanks for your reply. No worries about the delay, I'm not in a hurry either. I'll submit a PR shortly. 

Regards,

Marcel

**Comment by illegalprime** [comment]
#3 fixes this issue.
